#' Sample metadata table for RNA-seq experiment aboard ISS and on Earth
#'
#' @description
#'
#' [samples()] returns a metadata table for the 35 mouse retina samples
#' collected in a spaceflight experiment conducted aboard the International
#' Space Station (ISS) and in matched ground-based controls on Earth.
#' It includes key information about the biological specimen, experimental
#' condition, and physical acceleration environment in which the mice were
#' housed during the mission.
#'
#' @returns A tibble with 35 rows and 9 columns:
#'
#' \describe{
#'   \item{`sample_id`}{Unique identifier for each RNA-seq sample. Encodes group and replicate.}
#'   \item{`organism`}{Biological species. All samples are from *Mus musculus* (mouse).}
#'   \item{`sex`}{Sex of the animal. All samples in this dataset are from male mice.}
#'   \item{`matrix`}{Biological matrix from which RNA was extracted. In this dataset, all samples are from the right retina.}
#'   \item{`spacecraft`}{The platform or habitat in which the mouse was housed:
#'     \itemize{
#'       \item `"ISS"` — aboard the International Space Station.
#'       \item `"Earth"` — ground-based control under comparable conditions.
#'     }
#'     Note that the term "spacecraft" is used here to denote the physical environment supporting life during the experiment, including ground controls.}
#'   \item{`acceleration_source`}{Describes the physical mechanism by which the mouse experienced gravitational acceleration:
#'     \itemize{
#'       \item `"Terrestrial Gravity"` — natural 1G gravity at Earth's surface due to planetary mass.
#'       \item `"Centrifugal Acceleration"` — artificial gravity generated by rotating the mouse habitat in a centrifuge aboard the ISS.
#'       \item `"Orbital Free Fall"` — near-weightlessness resulting from continuous free fall in orbit (commonly referred to as _microgravity_).
#'     }
#'     This variable separates the *mechanism* of experienced acceleration from the *platform* (`spacecraft`).}
#'   \item{`gravity`}{Numeric representation of the effective gravitational acceleration (in multiples of Earth gravity, G) experienced by the sample. Values include:
#'     \itemize{
#'       \item `1` — either terrestrial 1G or 1G simulated via centrifuge on ISS.
#'       \item `0.66` or `0.33` — partial gravity simulated by adjusting centrifuge speed.
#'       \item `0.000001` — represents orbital free fall (a proxy for microgravity). Although gravitational pull is still ~90% of Earth’s at ISS altitude, this reflects the net effective acceleration in the free-fall frame.}
#'     This variable supports quantitative modeling of gravity-dependent effects.}
#'
#'   \item{`gravity_class`}{Effective gravity categories as a factor variable.}
#'
#'   \item{`weight_at_launch`}{Body weight of the animal at the time of launch (or analogous time point for ground controls), in grams.}
#'   \item{`weight_at_euthanasia`}{Body weight of the animal at euthanasia, in grams. Used to assess weight changes across experimental conditions.}
#' }
#'
#' @examples
#' samples()
#'
#' @export
samples <- function() {
  path <- dataset_path("samples")
  readr::read_rds(file = path)
}

